### ISSUE TITLE
failed pull of patchbay submodule. (solved)

### ISSUE THREAD

**Issue by toadzroc** [Houston4444/Patchance#1]
$ git submodule update --init
Submodule 'HoustonPatchbay' (git@github.com:Houston4444/HoustonPatchbay.git) registered for path 'HoustonPatchbay'
Cloning into '/home/alex/Downloads/git/Patchance/HoustonPatchbay'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:Houston4444/HoustonPatchbay.git' into submodule path '/home/alex/Downloads/git/Patchance/HoustonPatchbay' failed
Failed to clone 'HoustonPatchbay'. Retry scheduled
Cloning into '/home/alex/Downloads/git/Patchance/HoustonPatchbay'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:Houston4444/HoustonPatchbay.git' into submodule path '/home/alex/Downloads/git/Patchance/HoustonPatchbay' failed
Failed to clone 'HoustonPatchbay' a second time, aborting

**Comment by Houston4444** [comment]
Hi.
I don't really understand.
Have you tried:
`git clone --recurse-submodules https://github.com/Houston4444/Patchance.git`
or 
`git clone --recurse-submodules git@github.com:Houston4444/Patchance.git` ?

**Comment by toadzroc** [comment]
git clone --recurse-submodules https://github.com/Houston4444/Patchance.git
Cloning into 'Patchance'...
remote: Enumerating objects: 436, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 436 (delta 0), reused 3 (delta 0), pack-reused 432
Receiving objects: 100% (436/436), 5.27 MiB | 150.00 KiB/s, done.
Resolving deltas: 100% (227/227), done.
Submodule 'HoustonPatchbay' (git@github.com:Houston4444/HoustonPatchbay.git) registered for path 'HoustonPatchbay'
Cloning into '/home/alex/Downloads/git/Patchance/HoustonPatchbay'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:Houston4444/HoustonPatchbay.git' into submodule path '/home/alex/Downloads/git/Patchance/HoustonPatchbay' failed
Failed to clone 'HoustonPatchbay'. Retry scheduled
Cloning into '/home/alex/Downloads/git/Patchance/HoustonPatchbay'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:Houston4444/HoustonPatchbay.git' into submodule path '/home/alex/Downloads/git/Patchance/HoustonPatchbay' failed
Failed to clone 'HoustonPatchbay' a second time, aborting

**Comment by toadzroc** [comment]
git clone --recurse-submodules git@github.com:Houston4444/Patchance.git
Cloning into 'Patchance'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by toadzroc** [comment]
I'm open to further suggestions.

**Comment by Houston4444** [comment]
Sorry, for the moment I just don't know, @spotlightKid already has done a package for ArchLinux https://aur.archlinux.org/packages/patchance-git , so this should works. Have you configured an .ssh key for git ? 

https://github.com/settings/keys

I don't know if it is needed, that is just a hint.

**Comment by toadzroc** [comment]
Ok, adding an SSH key to my github account fixed it. I then used the https URL to pull  the code.

Patchance built ok, and i'll test it with JACK shortly.

Thanks for the help.

If there's others who encounter the same problem, we'll have a possible solution for them.

Alex.
